### ISSUE TITLE
The whole script is broken

### ISSUE THREAD

**Issue by rlaphoenix** [ahezard/twl_firm_patcher#1]
"cp" is only for Linux
And alot of Python files have UTF8 Encoding issues and more

**Comment by ahezard** [comment]
You need to have devkitpro installed. I agree I should mention it.

**Comment by ahezard** [comment]
You need python as well

**Comment by rlaphoenix** [comment]
Ahezard any chance you could patch mine? I really dont have time to install devkit and I dont like the mass amount of temp files it hard stores on HDD's.

Ill appreciate it a lot

**Comment by ahezard** [comment]
Well not there. The whole point of this is that:
- I do not want to publish decrypted nintendo stuff on my github
- to document how I did it so it can be implemented in future version of 3ds cfw. 

So Send me a pm on gbatemp and please remove that link.

**Comment by ghost** [comment]
I love this so much ahezard!! I was able to get NitroHax up and running! :) thank you so much!

**Comment by ahezard** [comment]
You are welcome SirBeethoven. Readme updated so I close the issue.
