### ISSUE TITLE
dosent seem to work properly

### ISSUE THREAD

**Issue by kristiansja** [ahezard/twl_firm_patcher#4]
C:\SCOURCES\twl_firm_patcher-master>mkdir temp\
A subdirectory or file temp\ already exists.

C:\SCOURCES\twl_firm_patcher-master>cp input\firmware_twl.bin temp\

C:\SCOURCES\twl_firm_patcher-master>cd scripts

C:\SCOURCES\twl_firm_patcher-master\scripts>patch_dev_launcher_o3ds.cmd

FIRM:
Signature:              BAD337785112C41EA0A05B84E61693A3A05D6117456BCBE808A6943E5B54471D
                        860ADEA44D0373E77C06BC409D610DC2D2A12CA10B4C4E1D9C112980DD01AACD
                        8856293325E5078EE0AB2BF69EDEFEFC70FB1B0BCA1D6C178E61D6356B3B3669
                        13F1676C69B2DC4538408E423A7B4B9F6CE1CD5D63FEB7441E02526865D34CD9
                        C95882F098D20B2DBD0AA6D4E958482A6DFA24E281E0480028C0C272DD98BF53
                        9121E3F28F71D610477D53DCDD659A8D4EB6A0030251E949185CB226C191EFBB
                        B5D76417E0CC763EEE916BE2559B3C85C71C1A96169549793040F2835C3DC8EC
                        10C81AC1E02CBBEE5665F493B15A93535AC87A87F90B460F462C32ECA6ABA302

Entrypoint ARM9:        0x0801301C
Entrypoint ARM11:       0x1FFAC01C

Section 0
 Type:                  ARM11
 Address:               0x18000000
 Offset:                0x00000200
 Size:                  0x0013B000
 Hash:                  0FDBBE41A88FFFECA5F88EF9702E844785670D5BA4B45446C1380965C94024A6
Section 1
 Type:                  ARM11
 Address:               0x1FF96000
 Offset:                0x0013B200
 Size:                  0x00015000
 Hash:                  12BFA273F058548625E65F686714CC2B946CE9ED01828F8044610FF49352809A
Section 2
 Type:                  ARM11
 Address:               0x1FFAB000
 Offset:                0x00150200
 Size:                  0x00003000
 Hash:                  A1FEDB7B8EEAA3DA72FB30B38A5C96F4575F60139370B5A3A2B6CAD900AAC35A
Section 3
 Type:                  ARM9
 Address:               0x08006800
 Offset:                0x00153200
 Size:                  0x00044C00
 Hash:                  2EB3E62C8E724DCC737F5040C53F122E9AF26E8D5C1723674A1F9BEFE4CAE6BF
Saving section 0 to firm/firm_0_18000000.bin...
Saving section 1 to firm/firm_1_1FF96000.bin...
Saving section 2 to firm/firm_2_1FFAB000.bin...
Saving section 3 to firm/firm_3_08006800.bin...
Press any key to continue . . .
save: twlBg.ncch.header
save: twlBg.exheader.bin
save: twlBg.exefs
save: twlBg.exefs.header
save: twlBg_original_exefs/code.bin
'python' is not recognized as an internal or external command,
operable program or batch file.
TWLTool v1.1
  by WulfyStylez
  Special thanks to CaitSith2

Input filename invalid!Nintendo DS rom tool 1.50.3 - Dec 12 2015
by Rafael Vuijk, Dave Murphy, Alexei Karpenko
9i (null), 7i (null), unitcode 0
'python' is not recognized as an internal or external command,
operable program or batch file.
Systemet finner ikke angitt fil.
TWLTool v1.1
  by WulfyStylez
  Special thanks to CaitSith2

Input filename invalid!A subdirectory or file twlBg_patched_exefs already exists.
'python' is not recognized as an internal or external command,
operable program or batch file.
load: twlBg.exefs.header
ERROR: open file twlBg_patched_exefs/code.bin failed

ERROR: create file failed

load: twlBg.ncch.header
load: twlBg.exheader.bin
load: twlBg_patched.exefs
Press any key to continue . . .

**Comment by ghost** [comment]
`python is not found`
You need Python in your PATH

**Comment by kristiansja** [comment]
still error,

`
C:\SCOURCES\twl_firm_patcher-master>mkdir temp\
A subdirectory or file temp\ already exists.

C:\SCOURCES\twl_firm_patcher-master>cp input\firmware_twl.bin temp\

C:\SCOURCES\twl_firm_patcher-master>cd scripts

C:\SCOURCES\twl_firm_patcher-master\scripts>patch_dev_launcher_o3ds.cmd

FIRM:
Signature:              BAD337785112C41EA0A05B84E61693A3A05D6117456BCBE808A6943E5B54471D
                        860ADEA44D0373E77C06BC409D610DC2D2A12CA10B4C4E1D9C112980DD01AACD
                        8856293325E5078EE0AB2BF69EDEFEFC70FB1B0BCA1D6C178E61D6356B3B3669
                        13F1676C69B2DC4538408E423A7B4B9F6CE1CD5D63FEB7441E02526865D34CD9
                        C95882F098D20B2DBD0AA6D4E958482A6DFA24E281E0480028C0C272DD98BF53
                        9121E3F28F71D610477D53DCDD659A8D4EB6A0030251E949185CB226C191EFBB
                        B5D76417E0CC763EEE916BE2559B3C85C71C1A96169549793040F2835C3DC8EC
                        10C81AC1E02CBBEE5665F493B15A93535AC87A87F90B460F462C32ECA6ABA302

Entrypoint ARM9:        0x0801301C
Entrypoint ARM11:       0x1FFAC01C

Section 0
 Type:                  ARM11
 Address:               0x18000000
 Offset:                0x00000200
 Size:                  0x0013B000
 Hash:                  0FDBBE41A88FFFECA5F88EF9702E844785670D5BA4B45446C1380965C94024A6
Section 1
 Type:                  ARM11
 Address:               0x1FF96000
 Offset:                0x0013B200
 Size:                  0x00015000
 Hash:                  12BFA273F058548625E65F686714CC2B946CE9ED01828F8044610FF49352809A
Section 2
 Type:                  ARM11
 Address:               0x1FFAB000
 Offset:                0x00150200
 Size:                  0x00003000
 Hash:                  A1FEDB7B8EEAA3DA72FB30B38A5C96F4575F60139370B5A3A2B6CAD900AAC35A
Section 3
 Type:                  ARM9
 Address:               0x08006800
 Offset:                0x00153200
 Size:                  0x00044C00
 Hash:                  2EB3E62C8E724DCC737F5040C53F122E9AF26E8D5C1723674A1F9BEFE4CAE6BF
Saving section 0 to firm/firm_0_18000000.bin...
Saving section 1 to firm/firm_1_1FF96000.bin...
Saving section 2 to firm/firm_2_1FFAB000.bin...
Saving section 3 to firm/firm_3_08006800.bin...
Press any key to continue . . .
save: twlBg.ncch.header
save: twlBg.exheader.bin
save: twlBg.exefs
save: twlBg.exefs.header
save: twlBg_original_exefs/code.bin
'python' is not recognized as an internal or external command,
operable program or batch file.
TWLTool v1.1
  by WulfyStylez
  Special thanks to CaitSith2

Input filename invalid!Nintendo DS rom tool 1.50.3 - Dec 12 2015
by Rafael Vuijk, Dave Murphy, Alexei Karpenko
9i (null), 7i (null), unitcode 0
'python' is not recognized as an internal or external command,
operable program or batch file.
Systemet finner ikke angitt fil.
TWLTool v1.1
  by WulfyStylez
  Special thanks to CaitSith2

Input filename invalid!A subdirectory or file twlBg_patched_exefs already exists.
'python' is not recognized as an internal or external command,
operable program or batch file.
load: twlBg.exefs.header
ERROR: open file twlBg_patched_exefs/code.bin failed

ERROR: create file failed

load: twlBg.ncch.header
load: twlBg.exheader.bin
load: twlBg_patched.exefs
Press any key to continue . . .`

**Comment by kristiansja** [comment]
just restarted and tried again, think it worked. 

EDIT: When starting Ntrohax it gives me the error screen of death

**Comment by ghost** [comment]
`'python' is not recognized as an internal or external command,
operable program or batch file.` You have to set in PATH.

**Comment by ahezard** [comment]
Please remove the temp folder and try again.

**Comment by ahezard** [comment]
Thanks for the support PokeAcer549. For the error in NitroHax it have to be related to luma. Are you using luma 6.0 dev kristiansja?

**Comment by kristiansja** [comment]
i am using dev 6.0.1. Java is set in path and works when typed "python" in cmd. Dont understand why people hatin. Still getting the error tough, no cart in slot 1, a9lh. sysnand

**Comment by ahezard** [comment]
So you get the patcher working in the end. And you can just use luma 6.1.1 (even the not dev version) without patching now. The issue you have with luma is most probably not related to this patch. I close this issue.
