### ISSUE TITLE
Possible derp

### ISSUE THREAD

**Issue by TuxSH** [ahezard/twl_firm_patcher#7]
> offset 0xA5888 replace 02 01 1A E3 08 60 87 05 by 08 62 86 E3 08 60 87 E5 (ARM7 SCFG unlock)

`08 62 86 E3 08 60 87 E5` assembles into:

``` asm
orr r6, #(1<<31)
str r6, [r7, #8] ; SCFG_EXT
```

I'm not sure whether it is an error or not (it should logically be `bic` and not `orr`). It is also probable that this code isn't reached at all. Either way, not setting this bit can possibly break DSi mode detection from the Arm7 (as described on Gbatek, section "DSi notes").

It's weird because the patch is required but the fact that it is `orr` or `bic` doesn't change anything...

**Comment by ahezard** [comment]
Yes the original patch force the bit 31 to 1 via an orr. You are saying that a bic have the same result in the end? Is the bic implemented in luma 6.1.1 ?

**Comment by ahezard** [comment]
Seems that with the information gathered with this project ApacheThunder got the TWL to NTR mode switch working :-) ApacheThunder/NTR_Launcher@18fdf50

This project is reaching his end, no patches will be needed in the end. It was very useful for research purpose though and may still be used for that in the future.

**Comment by TuxSH** [comment]
> You are saying that a bic have the same result in the end? Is the bic implemented in luma 6.1.1 ?

Yes
